// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Elmatgar.persistence.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editUsersAndCustomerHassanShaddad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editUsersAndCustomerHassanShaddad));
        
        string IMigrationMetadata.Id
        {
            get { return "201611012137219_editUsersAndCustomerHassanShaddad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
